### ISSUE TITLE
Form unmount memory leak

### ISSUE THREAD

**Issue by jayeclark** [jayeclark/banking#1]
Error message on app when beginning to fill out the contact form and then navigating away from the page.

index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at FormFormik (http://localhost:3000/banking/static/js/main.chunk.js:937:3)
    at div
    at div
    at Card (http://localhost:3000/banking/static/js/main.chunk.js:778:3)
    at CreateAccount (http://localhost:3000/banking/static/js/main.chunk.js:2196:75)

**Comment by jayeclark** [comment]
Fixed by removing the notification settings from the useState declaration. These would only change before the notification component is mounted, so should not be tracked to trigger a re-render to begin with. Only submitted triggers a rerender of the form component.

**Comment by jayeclark** [comment]
This is still happening. The issue is with the setTimeout function that makes the notification disappear. I believe the solution is a useEffect hook with a cleanup that sets mounted to false, and then setting the anonymous function in the submit handler to only run if mounted is true.

**Comment by jayeclark** [comment]
Fixed! It turned out to be easier to set a local variable that tracked whether the notification had been manually closed or not, and which notification was manually closed. 

Originally I was just tracking whether it had been closed or not, and firing the automatic close if `manuallyClosed = false`. However, every time a new component mounted, manuallyClosed would get set to false anyway as part of the new component. So, the solution was to make manually closed an object that tracked both the notification name and whether it had been manually closed... when a new component mounts, both values are overwritten, which means that the original setTimeout function will not fire (because it only fires if 'notification name' = the name of that notification and closed = false).

Another simpler option that I considered was changing where in the code manuallyClosed gets set to false. Specifically, declaring it as true by default, then changing it to 'false' right before the notification is sent. I think this could still create a situation where you get a notification in one component, close it out manually, then get another notification in another component and have the program be trying to update state in the previous component even though it has been unmounted.
